version: '3'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    container_name: yuotube-backend
    environment:
      - DUMMY_USER_ID=someid
      - AUTH0_CERT=somecert
      - APP_KEYS=somekey
      - ADMIN_JWT_SECRET=tobemodified
      - JWT_SECRET=tobemodified
      - API_TOKEN_SALT=somesalt
      - CORS_ORIGIN=*
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_SSL=false
    volumes:
      - upload:/app/public/uploads
    ports:
      - 80:1337

  db:
    image: postgres:15-alpine
    container_name: yuotube-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  upload: