version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: yuotube-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: yuotube-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
